DROP DATABASE IF EXISTS 4linux;

CREATE DATABASE 4linux;

USE 4linux;

CREATE TABLE cursos (
  id SMALLINT UNSIGNED PRIMARY KEY,
  nome VARCHAR(100) NOT NULL DEFAULT '',
  duracao TINYINT NOT NULL DEFAULT 0,
  valor FLOAT NOT NULL DEFAULT 0,
  cadastrado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  alterado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE professores (
  cpf CHAR(14) PRIMARY KEY,
  nome VARCHAR(100) NOT NULL DEFAULT '',
  email VARCHAR(100) NOT NULL DEFAULT '',
  nascimento DATE NOT NULL DEFAULT '1970-01-01',
  cadastrado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  alterado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE alunos (
  cpf CHAR(14) PRIMARY KEY,
  nome VARCHAR(100) NOT NULL DEFAULT '',
  email VARCHAR(100) NOT NULL DEFAULT '',
  telefone CHAR(17) NOT NULL DEFAULT '',
  nascimento DATE NOT NULL DEFAULT '1970-01-01',
  cadastrado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  alterado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE alunos_extras (
  cpf CHAR(14) PRIMARY KEY,
  endereco VARCHAR(255) NOT NULL DEFAULT '',
  cidade_id SMALLINT UNSIGNED NOT NULL,
  cep CHAR(9) NOT NULL DEFAULT '',
  site VARCHAR(255) NOT NULL DEFAULT '',
  cv TEXT
);

CREATE TABLE turmas (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  curso_id SMALLINT UNSIGNED NOT NULL,
  professor_cpf CHAR(14) NOT NULL DEFAULT '',
  inicio DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  fim DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00'
);

CREATE TABLE turmas_alunos (
  turma_id SMALLINT UNSIGNED NOT NULL,
  aluno_cpf CHAR(14) NOT NULL,
  PRIMARY KEY(turma_id, aluno_cpf)
);

CREATE TABLE alunos_compras (
  aluno_cpf CHAR(14) NOT NULL,
  turma_id MEDIUMINT UNSIGNED NOT NULL,
  valor FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY(aluno_cpf, turma_id)
);

CREATE TABLE estados (
  uf CHAR(2) NOT NULL PRIMARY KEY,
  nome VARCHAR(20) NOT NULL
);

CREATE TABLE cidades (
  id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  estado_uf CHAR(2) NOT NULL,
  nome VARCHAR(255) NOT NULL DEFAULT ''
);
